apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: api
    app.kubernetes.io/component: api
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: api
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: api
        app.kubernetes.io/component: api
    spec:
      terminationGracePeriodSeconds: 90
      containers:
        - image: api
          name: api
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 10m
              memory: 20Mi
          livenessProbe:
            httpGet:
              path: /v1/healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /v1/healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","sleep 15s"]
          volumeMounts:
            - mountPath: /tmp
              name: uploads
      volumes:
        - name: uploads
          emptyDir: {}
