apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: api
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: api
    app.kubernetes.io/component: api
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http